const BASE_THEMES = {
  Animals: [
    "LION", "BEAR", "WOLF", "DEER", "GOAT",
    "TIGER", "ZEBRA", "RHINO", "EAGLE", "SHARK", "WHALE", "KOALA", "PANDA", "HORSE", "CAMEL", "OTTER", "MOOSE", "SLOTH",
    "MONKEY", "IGUANA", "FALCON", "JAGUAR", "BADGER", "RABBIT", "BEAVER",
    "GIRAFFE", "PENGUIN", "DOLPHIN", "CHEETAH", "OCTOPUS", "GORILLA", "LEOPARD", "BUFFALO",
    "ELEPHANT", "KANGAROO", "FLAMINGO", "REINDEER", "ANTELOPE",
    "CROCODILE", "PORCUPINE", "BUTTERFLY",
  ],
  Fruits: [
    "FIG", "KIWI", "LIME", "PLUM", "PEAR", "DATE",
    "APPLE", "MANGO", "PEACH", "LEMON", "MELON", "GUAVA", "OLIVE", "BERRY",
    "BANANA", "ORANGE", "CHERRY", "GRAPES", "PAPAYA", "QUINCE", "LYCHEE",
    "APRICOT", "AVOCADO", "COCONUT", "KUMQUAT",
    "MULBERRY", "MANDARIN",
    "PINEAPPLE", "BLUEBERRY", "RASPBERRY", "NECTARINE", "TANGERINE", "JACKFRUIT",
    "STRAWBERRY", "WATERMELON", "BLACKBERRY", "GRAPEFRUIT", "CANTALOUPE",
    "POMEGRANATE",
  ],
  Countries: [
    "PERU", "CUBA", "IRAN", "IRAQ", "LAOS",
    "SPAIN", "CHINA", "INDIA", "ITALY", "JAPAN", "KENYA", "EGYPT", "CHILE", "GHANA", "NEPAL", "MALTA",
    "BRAZIL", "CANADA", "FRANCE", "GREECE", "MEXICO", "POLAND", "NORWAY", "TURKEY", "JORDAN", "RUSSIA", "TAIWAN",
    "DENMARK", "HUNGARY", "GERMANY", "AUSTRIA", "BELGIUM", "VIETNAM", "MOROCCO", "ECUADOR", "URUGUAY", "ICELAND", "FINLAND",
    "PORTUGAL", "THAILAND", "COLOMBIA", "MONGOLIA",
    "ARGENTINA", "AUSTRALIA", "SINGAPORE", "VENEZUELA", "INDONESIA", "CAMBODIA",
    "SWITZERLAND",
  ],
  Sports: [
    "GOLF", "JUDO", "POLO",
    "RUGBY", "TENNIS", "SOCCER", "HOCKEY", "BOXING", "SKIING", "KARATE", "DIVING", "ROWING",
    "CRICKET", "CYCLING", "SAILING", "SURFING", "FENCING", "ARCHERY", "BOWLING", "SKATING", "CURLING",
    "SOFTBALL", "FOOTBALL", "BASEBALL", "SWIMMING", "CLIMBING", "HANDBALL", "LACROSSE",
    "BADMINTON", "WRESTLING", "MARATHON", "TRIATHLON",
    "BASKETBALL", "VOLLEYBALL", "RACQUETBALL",
  ],
  Space: [
    "SUN", "STAR", "MOON", "MARS",
    "ORBIT", "COMET", "VENUS", "EARTH", "PLUTO", "SOLAR", "LUNAR",
    "COSMOS", "GALAXY", "NEBULA", "METEOR", "PLANET", "ROCKET", "SATURN", "URANUS", "QUASAR", "PULSAR", "CRATER",
    "ECLIPSE", "GRAVITY", "NEPTUNE", "MERCURY", "JUPITER", "STELLAR",
    "ASTEROID", "MILKYWAY", "STARDUST", "EQUINOX",
    "SATELLITE", "TELESCOPE", "ASTRONAUT", "SUPERNOVA", "BLACKHOLE", "HEMISPHERE",
  ],
  Music: [
    "TUBA", "HARP", "OBOE", "BASS",
    "PIANO", "DRUMS", "FLUTE", "CELLO", "CHORD", "BANJO", "ORGAN", "CHOIR", "TEMPO", "SCALE", "OPERA", "BUGLE", "TENOR", "VOCAL",
    "GUITAR", "VIOLIN", "MELODY", "RHYTHM", "SONATA", "BALLAD", "ANTHEM", "LYRICS", "SINGER",
    "TRUMPET", "HARMONY", "CONCERT", "MUSICAL",
    "CLARINET", "TROMBONE", "KEYBOARD",
    "SAXOPHONE", "ORCHESTRA", "ACCORDION", "CLASSICAL", "SYMPHONY",
  ],
  Tech: [
    "CHIP", "WIFI", "DATA", "CODE",
    "MOUSE", "CLOUD", "MODEM", "PIXEL", "CACHE", "ROBOT", "EMAIL", "PHONE",
    "ROUTER", "SERVER", "CODING", "LAPTOP", "SCREEN", "TABLET", "MEMORY", "BINARY", "PYTHON", "SOCKET", "DRIVER",
    "NETWORK", "MONITOR", "BROWSER", "DESKTOP", "STORAGE", "WEBSITE",
    "COMPUTER", "SOFTWARE", "INTERNET", "DATABASE", "KEYBOARD", "HARDWARE", "FIREWALL", "TERMINAL", "PROTOCOL",
    "ALGORITHM", "PROCESSOR", "JAVASCRIPT", "TYPESCRIPT",
    "PROGRAMMING",
  ],
  Nature: [
    "HILL", "LAKE", "POND", "CAVE", "TREE", "LEAF", "ROCK", "DUNE", "REEF",
    "MARSH", "CORAL", "CLIFF", "CREEK", "RIDGE", "GROVE", "BEACH", "STORM", "FJORD", "BLOOM",
    "RIVER", "OCEAN", "CANYON", "VALLEY", "ISLAND", "JUNGLE", "FOREST", "DESERT", "TUNDRA", "MEADOW", "STREAM", "LAGOON",
    "VOLCANO", "GLACIER", "BOULDER", "PRAIRIE", "WETLAND", "PLATEAU", "ICEBERG",
    "MOUNTAIN", "WOODLAND", "SAVANNAH",
    "WATERFALL", "RAINFOREST", "PENINSULA", "WILDERNESS",
  ],
} as const;

const MIX_WORDS = Array.from(
  new Set(Object.values(BASE_THEMES).flat() as string[]),
);

export const THEMES = {
  Mix: MIX_WORDS,
  ...BASE_THEMES,
} as Record<string, readonly string[]>;

export type ThemeName = "Mix" | keyof typeof BASE_THEMES;
export const THEME_NAMES = Object.keys(THEMES) as ThemeName[];

export type Difficulty = "Easy" | "Medium" | "Hard";

export const DIFFICULTY_SETTINGS = {
  Easy: { size: 8, directions: [[0, 1], [1, 0]], wordsCount: 6 },
  Medium: { size: 12, directions: [[0, 1], [1, 0], [1, 1], [-1, 1]], wordsCount: 8 },
  Hard: { size: 15, directions: [[0, 1], [1, 0], [1, 1], [-1, 1], [0, -1], [-1, 0], [-1, -1], [1, -1]], wordsCount: 12 }
};
